<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jeffrey Lee Shao Lin">
<meta name="dcterms.date" content="2024-10-28">

<title>ISSS626-GAA - Take Home Exercise 3a: Modelling Geography of Financial Inclusion with Geographically Weighted Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.1.html">
 <span class="dropdown-text">Hands-on Exercise 1.1: Geospatial Data Wrangling with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex1.2.html">
 <span class="dropdown-text">Hands-on Exercise 1.2: Choropleth Mapping with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.1.html">
 <span class="dropdown-text">Hands-on Exercise 2.1: 1st Order Spatial Point Patterns Analysis Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex2.2.html">
 <span class="dropdown-text">Hands-on Exercise 2.2: 2nd Order Spatial Point Patterns Analysis Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex3.html">
 <span class="dropdown-text">Hands-on Exercise 3: Network Constrained Spatial Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex4.html">
 <span class="dropdown-text">Hands-on Exercise 4: Spatial Weights and Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.1.html">
 <span class="dropdown-text">Hands-on Exercise 5.1: Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex5.2.html">
 <span class="dropdown-text">Hands-on Exercise 5.2: Local Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex6.html">
 <span class="dropdown-text">Hands-on Exercise 6: Geographical Segmentation with Spatially Constrained Clustering Techniques</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex7.html">
 <span class="dropdown-text">Hands-on Exercise 7: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex8.html">
 <span class="dropdown-text">Hands-on Exercise 8: Geographically Weighted Predictive Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex9.html">
 <span class="dropdown-text">Hands-on Exercise 9: Modelling Geographical Accessibility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.1.html">
 <span class="dropdown-text">Hands-on Exercise 10.1: Processing and Visualising Flow Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.2.html">
 <span class="dropdown-text">Hands-on Exercise 10.2: Calibrating Spatial Interaction Models with R</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html">
 <span class="dropdown-text">In-class Exercise 1: Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2: Spatial Point Patterns Analysis: spatstat methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3: Network Constrained Spatial Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4: Geographically Weighted Summary Statistics - gwModel methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5: Global and Local Measures of Spatial Autocorrelation: sfdep methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6: Emerging Hot Spot Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex08/In-class_Ex08.html">
 <span class="dropdown-text">In-class Exercise 8: Geographically Weighted Predictive Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex08/In-class_Ex08b.html">
 <span class="dropdown-text">In-class Exercise 8: Supplement</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex09/In-class_Ex09.html">
 <span class="dropdown-text">In-class Exercise 9: Modelling Geographical Accessibility</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex10/In-class_Ex10.html">
 <span class="dropdown-text">In-class Exercise 10: Working with Open Government Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html">
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html">
 <span class="dropdown-text">Take-Home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html">
 <span class="dropdown-text">Take-Home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#the-task" id="toc-the-task" class="nav-link" data-scroll-target="#the-task">2. The Task</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">3. The Data</a></li>
  <li><a href="#importing-packages" id="toc-importing-packages" class="nav-link" data-scroll-target="#importing-packages">4. Importing Packages</a></li>
  <li><a href="#getting-the-data-into-r-environment" id="toc-getting-the-data-into-r-environment" class="nav-link" data-scroll-target="#getting-the-data-into-r-environment">5. Getting the Data Into R Environment</a>
  <ul class="collapse">
  <li><a href="#importing-geospatial-data" id="toc-importing-geospatial-data" class="nav-link" data-scroll-target="#importing-geospatial-data">5.1 Importing geospatial data</a></li>
  <li><a href="#updating-crs-information" id="toc-updating-crs-information" class="nav-link" data-scroll-target="#updating-crs-information">5.1.1 Updating CRS Information</a></li>
  <li><a href="#importing-the-aspatial-data-finscope-uganda" id="toc-importing-the-aspatial-data-finscope-uganda" class="nav-link" data-scroll-target="#importing-the-aspatial-data-finscope-uganda">5.2 Importing the aspatial data, FinScope Uganda</a>
  <ul class="collapse">
  <li><a href="#variables-to-consider-for-financial-inclusion" id="toc-variables-to-consider-for-financial-inclusion" class="nav-link" data-scroll-target="#variables-to-consider-for-financial-inclusion">5.2.1 Variables to Consider for Financial Inclusion</a></li>
  <li><a href="#convert-to-percentage-and-log-transformations" id="toc-convert-to-percentage-and-log-transformations" class="nav-link" data-scroll-target="#convert-to-percentage-and-log-transformations">5.2.2 Convert to Percentage and Log-Transformations</a></li>
  </ul></li>
  <li><a href="#converting-aspatial-data-frame-into-a-sf-object" id="toc-converting-aspatial-data-frame-into-a-sf-object" class="nav-link" data-scroll-target="#converting-aspatial-data-frame-into-a-sf-object">5.3 Converting aspatial data frame into a sf object</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">6. Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#eda-using-statistical-graphics" id="toc-eda-using-statistical-graphics" class="nav-link" data-scroll-target="#eda-using-statistical-graphics">6.1 EDA using statistical graphics</a></li>
  <li><a href="#multiple-histogram-plots-distribution-of-variables" id="toc-multiple-histogram-plots-distribution-of-variables" class="nav-link" data-scroll-target="#multiple-histogram-plots-distribution-of-variables">6.2 Multiple Histogram Plots distribution of variables</a></li>
  </ul></li>
  <li><a href="#correlation-analysis---ggstatsplot-methods" id="toc-correlation-analysis---ggstatsplot-methods" class="nav-link" data-scroll-target="#correlation-analysis---ggstatsplot-methods">7. Correlation Analysis - ggstatsplot methods</a></li>
  <li><a href="#hedonic-pricing-modelling-in-r" id="toc-hedonic-pricing-modelling-in-r" class="nav-link" data-scroll-target="#hedonic-pricing-modelling-in-r">8. Hedonic Pricing Modelling in R</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-method" id="toc-simple-linear-regression-method" class="nav-link" data-scroll-target="#simple-linear-regression-method">8.1 Simple Linear Regression Method</a></li>
  <li><a href="#multiple-linear-regression-method" id="toc-multiple-linear-regression-method" class="nav-link" data-scroll-target="#multiple-linear-regression-method">8.2 Multiple Linear Regression Method</a>
  <ul class="collapse">
  <li><a href="#key-predictors" id="toc-key-predictors" class="nav-link" data-scroll-target="#key-predictors">Key Predictors</a></li>
  <li><a href="#non-significant-predictors" id="toc-non-significant-predictors" class="nav-link" data-scroll-target="#non-significant-predictors">Non-significant Predictors</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#preparing-publication-quality-table-olsrr-method" id="toc-preparing-publication-quality-table-olsrr-method" class="nav-link" data-scroll-target="#preparing-publication-quality-table-olsrr-method">9. Preparing Publication Quality Table: olsrr method</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take Home Exercise 3a: Modelling Geography of Financial Inclusion with Geographically Weighted Methods</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jeffrey Lee Shao Lin </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 28, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 14, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>According to&nbsp;<a href="https://en.wikipedia.org/wiki/Financial_inclusion">Wikipedia</a>,&nbsp;<strong>financial inclusion</strong>&nbsp;is the availability and equality of opportunities to access financial services. It refers to processes by which individuals and businesses can access appropriate, affordable, and timely financial products and services - which include banking, loan, equity, and insurance products. It provides paths to enhance inclusiveness in economic growth by enabling the unbanked population to access the means for savings, investment, and insurance towards improving household income and reducing income inequality.</p>
</section>
<section id="the-task" class="level1">
<h1>2. The Task</h1>
<p>In this take-home exercise, we are required to build an explanatory model to determine factors affecting <a href="https://www.bis.org/ifc/publ/ifcb47p.pdf">financial inclusion</a> by using geographical weighted regression methods.</p>
</section>
<section id="the-data" class="level1">
<h1>3. The Data</h1>
<p>For the purpose of this take-home exercise, two data sets shall be used, they are:</p>
<ul>
<li><p><a href="https://fsduganda.or.ug/data-sets-finscope-uganda-2023-survey-report/">FinScope Uganda 2023</a></p></li>
<li><p>The district level boundary GIS data can be downloaded from&nbsp;<a href="https://www.geoboundaries.org/">geoBoundaries</a>&nbsp;portal</p></li>
</ul>
</section>
<section id="importing-packages" class="level1">
<h1>4. Importing Packages</h1>
<p>Before we start the exercise, we will need to import necessary R packages first. We will use the following packages:</p>
<ul>
<li><p><a href="https://olsrr.rsquaredacademy.com/"><strong>olsrr</strong></a> package for building OLS and performing diagnostics tests</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/GWmodel/index.html"><strong>GWmodel</strong></a> package for calibrating geographical weighted family of models</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html"><strong>corrplot</strong></a> package for multivariate data visualisation and analysis</p></li>
<li><p><a href="https://r-spatial.github.io/sf/index.html">sf</a> package provides functions to manage, processing, and manipulate <strong>Simple Features</strong>, a formal geospatial data standard that specifies a storage and access model of spatial geometries such as points, lines, and polygons.</p></li>
<li><p><a href="https://cran.r-project.org/web/packages/tmap/index.html"><strong>tmap</strong></a> which provides functions for plotting cartographic quality static point patterns maps or interactive maps by using <a href="https://leafletjs.com/">leaflet</a> API.</p>
<p>Use the code chunk below to install and launch the below R packages.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(olsrr, ggstatsplot, corrplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="getting-the-data-into-r-environment" class="level1">
<h1>5. Getting the Data Into R Environment</h1>
<section id="importing-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-geospatial-data">5.1 Importing geospatial data</h2>
<p>The geospatial data used in this hands-on exercise is called geoBoundaries-UGA-ADM2. It is in ESRI shapefile format. The shapefile consists of Uganda district level boundaries. Polygon features are used to represent these geographic boundaries. The GIS data is in svy21 projected coordinates systems.</p>
<p>The code chunk below is used to import geoBoundaries-UGA-ADM2 shapefile by using st_read() of sf packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load district level boundary GIS data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>boundaries2 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/rawdata/geoBoundaries-UGA-ADM2-all"</span>, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">layer =</span> <span class="st">"geoBoundaries-UGA-ADM2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-UGA-ADM2' from data source 
  `C:\Users\user\OneDrive - Singapore Management University\MITB\6. Geospatial Analytics and Applications\jeffleesl\ISSS626-GAA\Take-Home_Ex\Take-Home_Ex03\data\rawdata\geoBoundaries-UGA-ADM2-all' 
  using driver `ESRI Shapefile'
Simple feature collection with 151 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 29.56838 ymin: -1.4732 xmax: 35.02676 ymax: 4.228399
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
<section id="updating-crs-information" class="level2">
<h2 class="anchored" data-anchor-id="updating-crs-information">5.1.1 Updating CRS Information</h2>
<p>Uganda is located in southeast Africa between 1º S and 4º N latitude, and between 30º E and 35º E longitude.</p>
<p>The code chunk below updates the newly imported mpsz with the correct ESPG code (i.e.&nbsp;32736 or 21096).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform to the correct ESPG Code</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>boundaries <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(boundaries2, <span class="dv">32736</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify the newly transformed boundaries</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(boundaries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32736 
  wkt:
PROJCRS["WGS 84 / UTM zone 36S",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 36S",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",33,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",10000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Navigation and medium accuracy spatial referencing."],
        AREA["Between 30°E and 36°E, southern hemisphere between 80°S and equator, onshore and offshore. Burundi. Eswatini (Swaziland). Kenya. Malawi. Mozambique. Rwanda. South Africa. Tanzania. Uganda. Zambia. Zimbabwe."],
        BBOX[-80,30,0,36]],
    ID["EPSG",32736]]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_bbox</span>(boundaries) <span class="co">#view extent</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      xmin       ymin       xmax       ymax 
  117997.3  9836930.8   725449.1 10467443.7 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(boundaries) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-1138447629.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Convert to multipolygon to individual polygon</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>boundaries_sf <span class="ot">&lt;-</span> boundaries <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"POLYGON"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area =</span> <span class="fu">st_area</span>(.))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in st_cast.sf(., "POLYGON"): repeating attributes for all
sub-geometries for which they may not be constant</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Group by the unique name and select the largest polygon by area</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>boundaries_cleaned <span class="ot">&lt;-</span> boundaries_sf <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(shapeName) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(area <span class="sc">==</span> <span class="fu">max</span>(area)) <span class="sc">%&gt;%</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>area) <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(shapeName) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">county_name =</span> shapeName </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(boundaries_cleaned) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-367677706.png" class="img-fluid"></p>
</section>
<section id="importing-the-aspatial-data-finscope-uganda" class="level2">
<h2 class="anchored" data-anchor-id="importing-the-aspatial-data-finscope-uganda">5.2 Importing the aspatial data, FinScope Uganda</h2>
<p>The FinScope-2023_Dataset_Final is in csv file format. The codes chunk below uses read_csv() function of readr package to import FinScope-2023_Dataset_Final into R as a tibble data frame called uganda_data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>uganda_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rawdata/FinScope-2023_Dataset_Final.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 3176 Columns: 686
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (25): HH_ID, Interview_ID, ea_name, District, Region, Subregion, Rural_...
dbl (638): ea_code, age, disabled, Pweight, Lhhid, Enum_code, InterviewDate,...
lgl  (23): f3_2_14, f3_2_15, f3_3_14, f3_3_15, f3_5_14, f3_5_15, g12_2_1, g1...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="variables-to-consider-for-financial-inclusion" class="level3">
<h3 class="anchored" data-anchor-id="variables-to-consider-for-financial-inclusion">5.2.1 Variables to Consider for Financial Inclusion</h3>
<p>Check the column names in the uganda_data to identify the right names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(uganda_data) <span class="co"># Displays all column names in the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To determine factors affecting financial inclusion, consider including the following types of variables:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Demographic Variables</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Economic Variables</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Geographic Variables</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">Access Variables</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">Financial Services Variables</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false">Other</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ul>
<li><p>Age and Age Band</p></li>
<li><p>Gender</p></li>
<li><p>Education Level</p></li>
<li><p>Mobile User</p></li>
</ul>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<ul>
<li><p>Income Level</p></li>
<li><p>Employment Status</p></li>
</ul>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<ul>
<li>Urban vs.&nbsp;rural status</li>
</ul>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<ul>
<li><p>Distance to nearest bank or financial institution from Home (Commercial Bank, SACCO and Mobile Money)</p></li>
<li><p>Distance to nearest ATM from Home</p></li>
</ul>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<ul>
<li><p>Financial Advice</p></li>
<li><p>Save Money and the channel (Commerical Nank, SACCO and Mobile Money)</p></li>
<li><p>Last amount saved</p></li>
<li><p>Borrow Money and the channel (Commerical Nank, SACCO and Mobile Money)</p></li>
<li><p>Last amount borrowed</p></li>
<li><p>Last amount sent</p></li>
<li><p>Last amount received</p></li>
</ul>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<ul>
<li><p>Documentation for KYC (National Identification Card, Passport, Utilities and Pay Slip)</p></li>
<li><p>Self Sustaining</p></li>
</ul>
</div>
</div>
</div>
<section id="rename-the-variables" class="level4">
<h4 class="anchored" data-anchor-id="rename-the-variables">5.2.1.1 Rename the Variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>uganda_data_rename <span class="ot">&lt;-</span> uganda_data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">11</span><span class="sc">:</span><span class="dv">17</span>, <span class="dv">20</span>, <span class="dv">23</span><span class="sc">:</span><span class="dv">28</span>, <span class="dv">30</span><span class="sc">:</span><span class="dv">34</span>, <span class="dv">36</span><span class="sc">:</span><span class="dv">37</span>, <span class="dv">40</span><span class="sc">:</span><span class="dv">43</span>, <span class="dv">45</span><span class="sc">:</span><span class="dv">63</span>, <span class="dv">65</span>, <span class="dv">67</span><span class="sc">:</span><span class="dv">90</span>, <span class="dv">93</span><span class="sc">:</span><span class="dv">94</span>, <span class="dv">96</span>, <span class="dv">98</span><span class="sc">:</span><span class="dv">167</span>, <span class="dv">169</span><span class="sc">:</span><span class="dv">230</span>, <span class="dv">232</span><span class="sc">:</span><span class="dv">234</span>, <span class="dv">236</span><span class="sc">:</span><span class="dv">238</span>, <span class="dv">240</span><span class="sc">:</span><span class="dv">241</span>, <span class="dv">243</span><span class="sc">:</span><span class="dv">342</span>, <span class="dv">344</span><span class="sc">:</span><span class="dv">364</span>, <span class="dv">366</span><span class="sc">:</span><span class="dv">384</span>, <span class="dv">386</span><span class="sc">:</span><span class="dv">438</span>, <span class="dv">440</span><span class="sc">:</span><span class="dv">444</span>, <span class="dv">448</span><span class="sc">:</span><span class="dv">473</span>, <span class="dv">476</span><span class="sc">:</span><span class="dv">674</span>, <span class="dv">677</span><span class="sc">:</span><span class="dv">679</span>, <span class="dv">681</span><span class="sc">:</span><span class="dv">686</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_band =</span> c1,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> c2,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">education_level =</span> c4,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">employment_status =</span> c5,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mobile_user =</span> c7_1_1,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">national_ic_doc =</span> c8_1a,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">passport_doc =</span> c8_1d,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">utilities_bill_doc =</span> c8_1e,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">pay_slip_doc =</span> c8_1j,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">self_sustaining =</span> e1_1,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">financial_advice =</span> e3_1,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money =</span> f2_1,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_commercial_bank =</span> f3_1_1,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_SACCO =</span> f3_1_4,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_mobile_money =</span> f3_1_6,</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_saved =</span> f6_1,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_borrowed =</span> g3_3,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_commercial_bank =</span> g6_1_1,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_SACCO =</span> g6_1_5,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_mobile_money =</span> g6_1_8,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_sent =</span> hpp3_2,</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_received =</span> hpp6_2,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">own_insurance =</span> j1,</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance_commerical_bank =</span> k1_1_1,</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance_SACCOS =</span> k1_1_7,</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance_ATM =</span> k1_1_8,</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">distance_mobile_money =</span> k1_1_9,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">savings_account =</span> kcb1_1_1,</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">joint_account =</span> kcb1_1_2, </span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">latitude =</span> hh_gps_latitude,</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">longitude =</span> hh_gps_longitude,</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> s1aq2b</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="clean-the-variables" class="level4">
<h4 class="anchored" data-anchor-id="clean-the-variables">5.2.1.1 Clean the Variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>uganda_data_new <span class="ot">&lt;-</span> uganda_data_rename <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(longitude) <span class="sc">&amp;</span> longitude <span class="sc">!=</span> <span class="st">""</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(latitude) <span class="sc">&amp;</span> latitude <span class="sc">!=</span> <span class="st">""</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_commercial_bank =</span> <span class="dv">2</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_SACCO =</span> <span class="dv">2</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_mobile_money =</span> <span class="dv">2</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_saved =</span> <span class="dv">9</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_borrowed =</span> <span class="dv">998</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_commercial_bank =</span> <span class="dv">2</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_SACCO =</span> <span class="dv">2</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_mobile_money =</span> <span class="dv">2</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_sent =</span> <span class="dv">998</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_amt_received =</span> <span class="dv">998</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(savings_account, joint_account), </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(.) <span class="sc">|</span> . <span class="sc">==</span> <span class="st">""</span>, <span class="dv">2</span>, .)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(uganda_data_new<span class="sc">$</span>longitude) <span class="co">#see the data in XCOORD column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.65414 33.65328 33.65403 33.65586 33.65472 33.65549</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(uganda_data_new<span class="sc">$</span>latitude) <span class="co">#see the data in YCOORD column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.677662 2.675690 2.673339 2.671343 2.671923 2.672423</code></pre>
</div>
</div>
<p>Next, summary() of base R is used to display the summary statistics of uganda_data_new tibble data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(uganda_data_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    HH_ID              Region          Rural_Urban           age_band    
 Length:3176        Length:3176        Length:3176        Min.   :1.000  
 Class :character   Class :character   Class :character   1st Qu.:3.000  
 Mode  :character   Mode  :character   Mode  :character   Median :4.000  
                                                          Mean   :3.986  
                                                          3rd Qu.:5.000  
                                                          Max.   :7.000  
     gender      education_level employment_status  mobile_user   
 Min.   :1.000   Min.   :1.000   Min.   : 1.00     Min.   :1.000  
 1st Qu.:1.000   1st Qu.:2.000   1st Qu.: 1.00     1st Qu.:1.000  
 Median :2.000   Median :3.000   Median : 2.00     Median :1.000  
 Mean   :1.552   Mean   :3.169   Mean   : 3.67     Mean   :1.273  
 3rd Qu.:2.000   3rd Qu.:4.000   3rd Qu.: 5.00     3rd Qu.:2.000  
 Max.   :2.000   Max.   :9.000   Max.   :99.00     Max.   :2.000  
 national_ic_doc  passport_doc  utilities_bill_doc  pay_slip_doc  
 Min.   :1.000   Min.   :1.00   Min.   :1.000      Min.   :1.000  
 1st Qu.:1.000   1st Qu.:2.00   1st Qu.:2.000      1st Qu.:2.000  
 Median :1.000   Median :2.00   Median :2.000      Median :2.000  
 Mean   :1.171   Mean   :1.96   Mean   :1.926      Mean   :1.964  
 3rd Qu.:1.000   3rd Qu.:2.00   3rd Qu.:2.000      3rd Qu.:2.000  
 Max.   :2.000   Max.   :2.00   Max.   :2.000      Max.   :2.000  
 self_sustaining financial_advice   save_money   save_money_commercial_bank
 Min.   :1.000   Min.   :1.000    Min.   :1.00   Min.   :1.000             
 1st Qu.:2.000   1st Qu.:1.000    1st Qu.:1.00   1st Qu.:2.000             
 Median :2.000   Median :1.000    Median :1.00   Median :2.000             
 Mean   :1.846   Mean   :1.401    Mean   :1.36   Mean   :1.896             
 3rd Qu.:2.000   3rd Qu.:2.000    3rd Qu.:2.00   3rd Qu.:2.000             
 Max.   :2.000   Max.   :2.000    Max.   :2.00   Max.   :2.000             
 save_money_SACCO save_money_mobile_money last_amt_saved  last_amt_borrowed
 Min.   :1.000    Min.   :1.000           Min.   :1.000   Min.   :  1.0    
 1st Qu.:2.000    1st Qu.:1.000           1st Qu.:1.000   1st Qu.:  3.0    
 Median :2.000    Median :2.000           Median :3.000   Median :998.0    
 Mean   :1.899    Mean   :1.738           Mean   :4.646   Mean   :626.1    
 3rd Qu.:2.000    3rd Qu.:2.000           3rd Qu.:9.000   3rd Qu.:998.0    
 Max.   :2.000    Max.   :2.000           Max.   :9.000   Max.   :998.0    
 borrow_money_commercial_bank borrow_money_SACCO borrow_money_mobile_money
 Min.   :1.000                Min.   :1.000      Min.   :1.000            
 1st Qu.:2.000                1st Qu.:2.000      1st Qu.:2.000            
 Median :2.000                Median :2.000      Median :2.000            
 Mean   :1.983                Mean   :1.978      Mean   :1.971            
 3rd Qu.:2.000                3rd Qu.:2.000      3rd Qu.:2.000            
 Max.   :2.000                Max.   :2.000      Max.   :2.000            
 last_amt_sent   last_amt_received own_insurance   distance_commerical_bank
 Min.   :  1.0   Min.   :  1.0     Min.   :1.000   Min.   :1.000           
 1st Qu.:  1.0   1st Qu.:  1.0     1st Qu.:2.000   1st Qu.:2.000           
 Median :998.0   Median :997.0     Median :2.000   Median :4.000           
 Mean   :582.9   Mean   :510.8     Mean   :1.974   Mean   :3.176           
 3rd Qu.:998.0   3rd Qu.:998.0     3rd Qu.:2.000   3rd Qu.:4.000           
 Max.   :998.0   Max.   :998.0     Max.   :2.000   Max.   :4.000           
 distance_SACCOS  distance_ATM   distance_mobile_money savings_account
 Min.   :1.000   Min.   :1.000   Min.   :1.000         Min.   :1.000  
 1st Qu.:2.000   1st Qu.:2.000   1st Qu.:1.000         1st Qu.:2.000  
 Median :2.000   Median :4.000   Median :1.000         Median :2.000  
 Mean   :2.508   Mean   :3.152   Mean   :1.655         Mean   :1.963  
 3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:2.000         3rd Qu.:2.000  
 Max.   :4.000   Max.   :4.000   Max.   :4.000         Max.   :2.000  
 joint_account    latitude         longitude     county_name       
 Min.   :1     Min.   :-1.4128   Min.   : 0.00   Length:3176       
 1st Qu.:2     1st Qu.: 0.2393   1st Qu.:30.99   Class :character  
 Median :2     Median : 0.7726   Median :32.54   Mode  :character  
 Mean   :2     Mean   : 0.9945   Mean   :31.53                     
 3rd Qu.:2     3rd Qu.: 1.9143   3rd Qu.:33.52                     
 Max.   :2     Max.   : 3.6876   Max.   :34.96                     </code></pre>
</div>
</div>
</section>
</section>
<section id="convert-to-percentage-and-log-transformations" class="level3">
<h3 class="anchored" data-anchor-id="convert-to-percentage-and-log-transformations">5.2.2 Convert to Percentage and Log-Transformations</h3>
<p>This will help to perform the geographical weighted regression methods later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>uganda_data_fin <span class="ot">&lt;-</span> uganda_data_new <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_age_band =</span> <span class="fu">log</span>(age_band),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender_pct =</span> gender <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_education_level =</span> <span class="fu">log</span>(education_level),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_employment_status =</span> <span class="fu">log</span>(employment_status),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mobile_user_pct =</span> mobile_user <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">national_ic_doc_pct =</span> national_ic_doc <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">passport_doc_pct =</span> passport_doc <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">utilities_bill_do_pct =</span> utilities_bill_doc <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">pay_slip_doc_pct =</span> pay_slip_doc <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">self_sustaining_pct =</span> self_sustaining <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">financial_advice_pct =</span> financial_advice <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_pct =</span> save_money <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_commercial_bank_pct =</span> save_money_commercial_bank <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_SACCO_pct =</span> save_money_SACCO <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">save_money_mobile_money_pct =</span> save_money_mobile_money <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_last_amt_saved =</span> <span class="fu">log</span>(last_amt_saved),</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_last_amt_borrowed =</span> <span class="fu">log</span>(last_amt_borrowed),</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_commercial_bank_pct =</span> borrow_money_commercial_bank <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_SACCO_pct =</span> borrow_money_SACCO <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">borrow_money_mobile_money_pct =</span> borrow_money_mobile_money <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_last_amt_sent =</span> <span class="fu">log</span>(last_amt_sent),</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_last_amt_received =</span> <span class="fu">log</span>(last_amt_received),</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">own_insurance_pct =</span> own_insurance <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_distance_commerical_bank =</span> <span class="fu">log</span>(distance_commerical_bank),</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_distance_SACCOS =</span> <span class="fu">log</span>(distance_SACCOS),</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_distance_ATM =</span> <span class="fu">log</span>(distance_ATM),</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">LOG_distance_mobile_money =</span> <span class="fu">log</span>(distance_mobile_money),</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">savings_account_pct =</span> savings_account <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">joint_account_pct =</span> joint_account <span class="sc">/</span> <span class="dv">3176</span> <span class="sc">*</span> <span class="dv">100</span> </span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="converting-aspatial-data-frame-into-a-sf-object" class="level2">
<h2 class="anchored" data-anchor-id="converting-aspatial-data-frame-into-a-sf-object">5.3 Converting aspatial data frame into a sf object</h2>
<p>Currently, the uganda_data_new tibble data frame is aspatial. We will convert it to a sf object. The code chunk below converts uganda_data_new data frame into a simple feature data frame by using st_as_sf() of sf packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>uganda_data.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(uganda_data_fin,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs=</span><span class="dv">32736</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that st_transform() of sf package is used to convert the coordinates from wgs84 (i.e.&nbsp;crs:4326) to Arc 1960 (i.e.&nbsp;crs=32736).</p>
<p>Next, head() is used to list the content of uganda_data.sf object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(uganda_data.sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 62 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 572616.1 ymin: 10295290 xmax: 572903.6 ymax: 10295980
Projected CRS: WGS 84 / UTM zone 36S
# A tibble: 6 × 63
  HH_ID  Region   Rural_Urban age_band gender education_level employment_status
  &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;           &lt;dbl&gt;             &lt;dbl&gt;
1 001001 NORTHERN Urban              4      2               6                 1
2 001019 NORTHERN Urban              4      2               2                 5
3 001028 NORTHERN Urban              3      2               1                 5
4 001037 NORTHERN Urban              4      1               2                 1
5 001040 NORTHERN Urban              4      2               3                 4
6 001047 NORTHERN Urban              1      1               2                 9
# ℹ 56 more variables: mobile_user &lt;dbl&gt;, national_ic_doc &lt;dbl&gt;,
#   passport_doc &lt;dbl&gt;, utilities_bill_doc &lt;dbl&gt;, pay_slip_doc &lt;dbl&gt;,
#   self_sustaining &lt;dbl&gt;, financial_advice &lt;dbl&gt;, save_money &lt;dbl&gt;,
#   save_money_commercial_bank &lt;dbl&gt;, save_money_SACCO &lt;dbl&gt;,
#   save_money_mobile_money &lt;dbl&gt;, last_amt_saved &lt;dbl&gt;,
#   last_amt_borrowed &lt;dbl&gt;, borrow_money_commercial_bank &lt;dbl&gt;,
#   borrow_money_SACCO &lt;dbl&gt;, borrow_money_mobile_money &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Notice that the output is in point feature data frame.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>6. Exploratory Data Analysis (EDA)</h1>
<p>Use statistical graphics functions of ggplot2 package to perform EDA</p>
<section id="eda-using-statistical-graphics" class="level2">
<h2 class="anchored" data-anchor-id="eda-using-statistical-graphics">6.1 EDA using statistical graphics</h2>
<p>Plot the distribution of accounts by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">savings_account_pct</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"light blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-1926521833.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">save_money_mobile_money_pct</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0B2130"</span>, <span class="at">fill=</span><span class="st">"#AB88BA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-2396109935.png" class="img-fluid"></p>
</section>
<section id="multiple-histogram-plots-distribution-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="multiple-histogram-plots-distribution-of-variables">6.2 Multiple Histogram Plots distribution of variables</h2>
<p>Draw a few multiple histograms (also known as trellis plot) by using ggarrange() of ggpubr package to analysis the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>LOG_age_band <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_age_band</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>gender_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">gender_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>LOG_education_level <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_education_level</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>LOG_employment_status <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_employment_status</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)  </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>mobile_user_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">mobile_user_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>national_ic_doc_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">national_ic_doc_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>passport_doc_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">passport_doc_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>utilities_bill_do_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">utilities_bill_do_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>pay_slip_doc_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">pay_slip_doc_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>self_sustaining_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">self_sustaining_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>financial_advice_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">financial_advice_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)    </span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>save_money_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">save_money_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)    </span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>save_money_commercial_bank_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">save_money_commercial_bank_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>)   </span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>save_money_SACCO_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">save_money_SACCO_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>save_money_mobile_money_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">save_money_mobile_money_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"#FFC166"</span>) </span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(LOG_age_band, gender_pct, LOG_education_level, LOG_employment_status, </span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>          mobile_user_pct, national_ic_doc_pct, passport_doc_pct, utilities_bill_do_pct, </span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a>          pay_slip_doc_pct, self_sustaining_pct, financial_advice_pct, save_money_pct, </span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>          save_money_commercial_bank_pct, save_money_SACCO_pct, save_money_mobile_money_pct, </span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-1805352332.png" class="img-fluid" width="914"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>LOG_last_amt_saved <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_last_amt_saved</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>) </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>LOG_last_amt_borrowed <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_last_amt_borrowed</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>borrow_money_commercial_bank_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">borrow_money_commercial_bank_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>borrow_money_SACCO_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">borrow_money_SACCO_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>borrow_money_mobile_money_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">borrow_money_mobile_money_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>LOG_last_amt_sent <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_last_amt_sent</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>LOG_last_amt_received <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_last_amt_received</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>own_insurance_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">own_insurance_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>LOG_distance_commerical_bank <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_distance_commerical_bank</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>LOG_distance_SACCOS <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_distance_SACCOS</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>LOG_distance_ATM <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_distance_ATM</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a>LOG_distance_mobile_money <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">LOG_distance_mobile_money</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>savings_account_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">savings_account_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>joint_account_pct <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>uganda_data.sf, <span class="fu">aes</span>(<span class="at">x=</span> <span class="st">`</span><span class="at">joint_account_pct</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>, <span class="at">color=</span><span class="st">"#0A1E0F"</span>, <span class="at">fill=</span><span class="st">"#A9CB9F"</span>)</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(LOG_last_amt_saved, LOG_last_amt_borrowed, borrow_money_commercial_bank_pct, borrow_money_SACCO_pct, </span>
<span id="cb33-44"><a href="#cb33-44" aria-hidden="true" tabindex="-1"></a>          borrow_money_mobile_money_pct, LOG_last_amt_sent, LOG_last_amt_received, own_insurance_pct, </span>
<span id="cb33-45"><a href="#cb33-45" aria-hidden="true" tabindex="-1"></a>          LOG_distance_commerical_bank, LOG_distance_SACCOS, LOG_distance_ATM, LOG_distance_mobile_money, </span>
<span id="cb33-46"><a href="#cb33-46" aria-hidden="true" tabindex="-1"></a>          savings_account_pct, joint_account_pct,</span>
<span id="cb33-47"><a href="#cb33-47" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">4</span>, <span class="at">nrow =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-3608888018.png" class="img-fluid" width="738">The plots show that the majority of people lack insurance, savings, and joint accounts. Many respondents also feel they do not have enough money and would like to seek financial advice. Additionally, a large portion of those surveyed report that bank branches and ATMs are located relatively far from their homes.</p>
</section>
</section>
<section id="correlation-analysis---ggstatsplot-methods" class="level1">
<h1>7. Correlation Analysis - ggstatsplot methods</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrmat</span>(uganda_data_fin[, <span class="dv">47</span><span class="sc">:</span><span class="dv">59</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/clipboard-4134350256.png" class="img-fluid"></p>
</section>
<section id="hedonic-pricing-modelling-in-r" class="level1">
<h1>8. Hedonic Pricing Modelling in R</h1>
<section id="simple-linear-regression-method" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-method">8.1 Simple Linear Regression Method</h2>
<p>Build a simple linear regression model by using savings_account_pct as the dependent variable and LOG_distance_commerical_bank as the independent variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>uganda.slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula=</span>savings_account_pct <span class="sc">~</span> LOG_distance_commerical_bank, <span class="at">data =</span> uganda_data.sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(uganda.slr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = savings_account_pct ~ LOG_distance_commerical_bank, 
    data = uganda_data.sf)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0309296  0.0005565  0.0005565  0.0019347  0.0033128 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  0.0596595  0.0002987 199.745  &lt; 2e-16 ***
LOG_distance_commerical_bank 0.0019882  0.0002574   7.723 1.51e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.005854 on 3174 degrees of freedom
Multiple R-squared:  0.01845,   Adjusted R-squared:  0.01814 
F-statistic: 59.65 on 1 and 3174 DF,  p-value: 1.509e-14</code></pre>
</div>
</div>
<p>The output report reveals that the SELLING_PRICE can be explained by using the formula:</p>
<pre><code>      *y = 0.0596595 + 0.0019882x1*</code></pre>
<p>The R-squared of 0.01845 reveals that the simple regression model built is able to explain about 1.845% of the percentage of having savings account.</p>
<p>Since p-value is way bigger than 0.0001, we will not reject the null hypothesis that mean is not a good estimator of percentage of having savings account.</p>
</section>
<section id="multiple-linear-regression-method" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-method">8.2 Multiple Linear Regression Method</h2>
<p>The code chunk below using lm() to calibrate the multiple linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>sa_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> savings_account_pct <span class="sc">~</span> LOG_age_band <span class="sc">+</span> gender_pct <span class="sc">+</span> LOG_education_level <span class="sc">+</span> LOG_employment_status <span class="sc">+</span> mobile_user_pct <span class="sc">+</span> national_ic_doc_pct <span class="sc">+</span> passport_doc_pct <span class="sc">+</span> utilities_bill_do_pct <span class="sc">+</span> pay_slip_doc_pct <span class="sc">+</span> self_sustaining_pct <span class="sc">+</span> financial_advice_pct <span class="sc">+</span>save_money_pct <span class="sc">+</span> save_money_commercial_bank_pct <span class="sc">+</span> save_money_SACCO_pct <span class="sc">+</span> save_money_mobile_money_pct <span class="sc">+</span> LOG_last_amt_saved <span class="sc">+</span> LOG_last_amt_borrowed <span class="sc">+</span> borrow_money_commercial_bank_pct <span class="sc">+</span> borrow_money_SACCO_pct <span class="sc">+</span> borrow_money_mobile_money_pct <span class="sc">+</span> LOG_last_amt_sent <span class="sc">+</span> LOG_last_amt_received <span class="sc">+</span> LOG_distance_commerical_bank <span class="sc">+</span> LOG_distance_SACCOS <span class="sc">+</span> LOG_distance_ATM <span class="sc">+</span> LOG_distance_mobile_money <span class="sc">+</span> joint_account_pct, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>uganda_data.sf)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sa_mlr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = savings_account_pct ~ LOG_age_band + gender_pct + 
    LOG_education_level + LOG_employment_status + mobile_user_pct + 
    national_ic_doc_pct + passport_doc_pct + utilities_bill_do_pct + 
    pay_slip_doc_pct + self_sustaining_pct + financial_advice_pct + 
    save_money_pct + save_money_commercial_bank_pct + save_money_SACCO_pct + 
    save_money_mobile_money_pct + LOG_last_amt_saved + LOG_last_amt_borrowed + 
    borrow_money_commercial_bank_pct + borrow_money_SACCO_pct + 
    borrow_money_mobile_money_pct + LOG_last_amt_sent + LOG_last_amt_received + 
    LOG_distance_commerical_bank + LOG_distance_SACCOS + LOG_distance_ATM + 
    LOG_distance_mobile_money + joint_account_pct, data = uganda_data.sf)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.032541 -0.000754 -0.000117  0.000530  0.016876 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                       2.212e-02  1.009e-02   2.193  0.02841 *  
LOG_age_band                     -1.489e-04  2.251e-04  -0.661  0.50854    
gender_pct                       -6.663e-03  5.831e-03  -1.143  0.25325    
LOG_education_level              -1.725e-04  1.855e-04  -0.930  0.35259    
LOG_employment_status             6.847e-05  1.123e-04   0.610  0.54194    
mobile_user_pct                  -7.065e-03  7.521e-03  -0.939  0.34755    
national_ic_doc_pct              -1.000e-03  8.438e-03  -0.119  0.90567    
passport_doc_pct                  4.086e-02  1.547e-02   2.642  0.00828 ** 
utilities_bill_do_pct             2.092e-02  1.186e-02   1.763  0.07792 .  
pay_slip_doc_pct                  4.974e-02  1.600e-02   3.110  0.00189 ** 
self_sustaining_pct               2.396e-02  8.176e-03   2.931  0.00341 ** 
financial_advice_pct              2.178e-03  6.152e-03   0.354  0.72338    
save_money_pct                   -6.590e-02  1.206e-02  -5.463 5.04e-08 ***
save_money_commercial_bank_pct    1.816e-01  1.099e-02  16.530  &lt; 2e-16 ***
save_money_SACCO_pct              2.195e-01  1.037e-02  21.158  &lt; 2e-16 ***
save_money_mobile_money_pct      -1.070e-02  7.546e-03  -1.418  0.15632    
LOG_last_amt_saved                5.387e-04  1.739e-04   3.098  0.00197 ** 
LOG_last_amt_borrowed             4.239e-05  3.228e-05   1.313  0.18920    
borrow_money_commercial_bank_pct  8.934e-02  2.279e-02   3.920 9.03e-05 ***
borrow_money_SACCO_pct            9.115e-02  2.028e-02   4.494 7.23e-06 ***
borrow_money_mobile_money_pct     4.941e-02  1.743e-02   2.835  0.00461 ** 
LOG_last_amt_sent                 5.258e-05  3.416e-05   1.539  0.12381    
LOG_last_amt_received            -2.109e-05  3.265e-05  -0.646  0.51834    
LOG_distance_commerical_bank      1.280e-03  4.694e-04   2.727  0.00643 ** 
LOG_distance_SACCOS              -4.183e-05  2.315e-04  -0.181  0.85664    
LOG_distance_ATM                 -6.954e-04  4.648e-04  -1.496  0.13473    
LOG_distance_mobile_money        -4.169e-06  2.132e-04  -0.020  0.98440    
joint_account_pct                -6.535e-02  1.570e-01  -0.416  0.67730    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.004901 on 3148 degrees of freedom
Multiple R-squared:  0.3177,    Adjusted R-squared:  0.3118 
F-statistic: 54.28 on 27 and 3148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The Multiple R-squared is 0.3177, suggesting that around 31.7% of the variability in savings_account_pct is explained by the predictor variables in the model. The Adjusted R-squared is 0.3118, which accounts for the number of predictors, confirming that the model provides a modest fit.</p>
<p>Whereas, The F-statistic of 54.28 with a very low p-value (&lt; 2.2e-16) indicates that the model is statistically significant overall, meaning at least one of the predictors significantly impacts the savings_account_pct.</p>
<section id="key-predictors" class="level3">
<h3 class="anchored" data-anchor-id="key-predictors">Key Predictors</h3>
<p>The coefficients tell us the direction and strength of each predictor’s relationship with <code>savings_account_pct</code>. Here are some significant predictors:</p>
<ol type="1">
<li><p><strong>Passport Documentation</strong> (<code>passport_doc_pct</code>, p = 0.00828):</p>
<ul>
<li>Positive relationship (Estimate = 0.0409): A higher percentage of individuals with passport documentation is associated with an increase in <code>savings_account_pct</code>.</li>
</ul></li>
<li><p><strong>Payslip Documentation</strong> (<code>pay_slip_doc_pct</code>, p = 0.00189):</p>
<ul>
<li>Positive relationship (Estimate = 0.0497): A higher percentage of individuals with pay slip documentation correlates with a higher percentage of savings accounts. This might suggest that stable income documentation positively influences savings account ownership.</li>
</ul></li>
<li><p><strong>Self-Sustaining Percentage</strong> (<code>self_sustaining_pct</code>, p = 0.00341):</p>
<ul>
<li>Positive relationship (Estimate = 0.0239): This suggests that communities with higher self-sustaining individuals are more likely to have savings accounts.</li>
</ul></li>
<li><p><strong>Saving with Commercial Banks and SACCOs</strong>:</p>
<ul>
<li><p><strong>Save Money<br>
</strong>(<code>save_money_pct,</code>p = 5.04e-08, Estimate = -0.06590): has a negative coefficient, implying that higher rates of people saving money in general are associated with a lower savings account percentage, possibly indicating other informal</p></li>
<li><p><strong>Save Money with Commercial Bank Percentage</strong> (<code>save_money_commercial_bank_pct</code>, p &lt; 2e-16, Estimate = 0.1816): Strong positive relationship, indicating that those who save with commercial banks are highly likely to have a savings account.</p></li>
<li><p><strong>Save Money with SACCO Percentage</strong> (<code>save_money_SACCO_pct</code>, p &lt; 2e-16, Estimate = 0.2195): Also a strong positive relationship, reinforcing that participation in SACCOs (Savings and Credit Cooperative Organizations) is a strong indicator of savings account ownership.</p></li>
</ul></li>
<li><p><strong>Borrowing from Commercial Banks and SACCOs</strong>:</p>
<ul>
<li><p><strong>Borrow Money from Commercial Bank Percentage</strong> (<code>borrow_money_commercial_bank_pct</code>, p = 9.03e-05, Estimate = 0.0893): Indicates a positive association with savings account ownership.</p></li>
<li><p><strong>Borrow Money from SACCO Percentage</strong> (<code>borrow_money_SACCO_pct</code>, p = 7.23e-06, Estimate = 0.0912): Similar positive relationship, suggesting that access to borrowing services is linked to having savings accounts.</p></li>
</ul></li>
<li><p><strong>Distance to Commercial Bank</strong> (<code>LOG_distance_commercial_bank</code>, p = 0.00643):</p>
<ul>
<li>Positive relationship (Estimate = 0.0013): As the log-distance to commercial banks increases, there’s a small but significant increase in the savings account percentage, which might suggest limited access drives individuals to hold savings accounts if they are already banked.</li>
</ul></li>
<li><p><strong>Last Amount Saved</strong> (<code>LOG_last_amt_saved</code>, p = 0.00197):</p>
<ul>
<li>Positive relationship (Estimate = 0.00054): The log of the last amount saved has a slight positive effect on savings account ownership, suggesting that recent saving activity is associated with having a savings account.</li>
</ul></li>
</ol>
</section>
<section id="non-significant-predictors" class="level3">
<h3 class="anchored" data-anchor-id="non-significant-predictors">Non-significant Predictors</h3>
<p>Some predictors, such as <code>gender_pct</code>, <code>LOG_education_level</code>, and <code>LOG_age_band</code>, show non-significant effects (high p-values). This may suggest that demographic factors like age, gender, and education do not directly impact the likelihood of savings account ownership in this context.</p>
<ul>
<li><p>Documentation (like passports and pay slips) and income stability appear to be important indicators of savings account ownership.</p></li>
<li><p>Engagement with formal and semi-formal financial services, such as commercial banks and SACCOs, positively influences the likelihood of having a savings account.</p></li>
<li><p>Access to borrowing services is also positively linked to savings account ownership, suggesting that people who have access to credit may be more financially integrated.</p></li>
<li><p>Distance to financial services can have a minor influence, suggesting a possible need for financial services closer to communities to further increase account ownership rates.</p></li>
</ul>
<p>In conclusion, the model suggests that factors related to financial habits (saving and borrowing with formal institutions) and access to financial documentation have significant impacts on the likelihood of savings account ownership in Uganda.</p>
</section>
</section>
</section>
<section id="preparing-publication-quality-table-olsrr-method" class="level1">
<h1>9. Preparing Publication Quality Table: olsrr method</h1>
<p>With reference to the report above, it is clear that not all the independent variables are statistically significant. We will revised the model by removing those variables which are not statistically significant.</p>
<p>Now, we are ready to calibrate the revised model by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sa_mlr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> savings_account_pct <span class="sc">~</span> passport_doc_pct <span class="sc">+</span> pay_slip_doc_pct  <span class="sc">+</span> self_sustaining_pct <span class="sc">+</span> save_money_pct <span class="sc">+</span> save_money_commercial_bank_pct <span class="sc">+</span> save_money_SACCO_pct <span class="sc">+</span> LOG_last_amt_saved <span class="sc">+</span> borrow_money_commercial_bank_pct <span class="sc">+</span> borrow_money_SACCO_pct <span class="sc">+</span> borrow_money_mobile_money_pct <span class="sc">+</span> LOG_distance_commerical_bank, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>uganda_data.sf)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_regress</span>(sa_mlr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Model Summary                            
------------------------------------------------------------------
R                       0.560       RMSE                    0.005 
R-Squared               0.314       MSE                     0.000 
Adj. R-Squared          0.312       Coef. Var               7.928 
Pred R-Squared          0.298       AIC                -24754.869 
MAE                     0.002       SBC                -24676.045 
------------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                                ANOVA                                  
----------------------------------------------------------------------
               Sum of                                                 
              Squares          DF    Mean Square       F         Sig. 
----------------------------------------------------------------------
Regression      0.035          11          0.003    131.713    0.0000 
Residual        0.076        3164          0.000                      
Total           0.111        3175                                     
----------------------------------------------------------------------

                                             Parameter Estimates                                              
-------------------------------------------------------------------------------------------------------------
                           model      Beta    Std. Error    Std. Beta      t        Sig      lower     upper 
-------------------------------------------------------------------------------------------------------------
                     (Intercept)     0.017         0.002                  8.139    0.000     0.013     0.021 
                passport_doc_pct     0.047         0.015        0.049     3.112    0.002     0.017     0.076 
                pay_slip_doc_pct     0.054         0.016        0.053     3.412    0.001     0.023     0.084 
             self_sustaining_pct     0.023         0.008        0.044     2.841    0.005     0.007     0.038 
                  save_money_pct    -0.066         0.011       -0.168    -5.772    0.000    -0.088    -0.043 
  save_money_commercial_bank_pct     0.183         0.011        0.299    17.371    0.000     0.163     0.204 
            save_money_SACCO_pct     0.219         0.010        0.353    21.723    0.000     0.200     0.239 
              LOG_last_amt_saved     0.001         0.000        0.097     3.502    0.000     0.000     0.001 
borrow_money_commercial_bank_pct     0.095         0.023        0.066     4.208    0.000     0.051     0.140 
          borrow_money_SACCO_pct     0.096         0.020        0.075     4.761    0.000     0.056     0.135 
   borrow_money_mobile_money_pct     0.050         0.017        0.044     2.914    0.004     0.016     0.083 
    LOG_distance_commerical_bank     0.001         0.000        0.044     2.937    0.003     0.000     0.001 
-------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>After added the independent variables which are statistically significant, there are no improvement in the R-Squared and Adjusted R-Squared. Furthermore, Predicted R-Squared (of 0.298) indicating that the model may perform slightly less effectively on unseen data. Both RMSE (of 0.005) and MAE (of 0.002) giving an idea of the typical error magnitude. However, AIC and SIC show lower values indicates a better fit given model complexity.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>